[2020-02-01 22:00:01,677] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 10.1.7.190:9092 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:296)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:250)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2020-02-01 22:15:06,060] WARN Client session timed out, have not heard from server in 11964ms for sessionid 0x1000101245f0005 (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:06,185] INFO Client session timed out, have not heard from server in 11964ms for sessionid 0x1000101245f0005, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,426] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,427] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:64353, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,436] WARN Unable to reconnect to ZooKeeper service, session 0x1000101245f0005 has expired (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,436] INFO Unable to reconnect to ZooKeeper service, session 0x1000101245f0005 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,437] INFO EventThread shut down for session: 0x1000101245f0005 (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,438] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2020-02-01 22:15:07,440] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2020-02-01 22:15:07,441] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@28eaa59a (org.apache.zookeeper.ZooKeeper)
[2020-02-01 22:15:07,444] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2020-02-01 22:15:07,445] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,446] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,448] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:64356, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,455] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 0x1000101245f0006, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2020-02-01 22:15:07,471] INFO Creating /brokers/ids/2 (is it secure? false) (kafka.zk.KafkaZkClient)
[2020-02-01 22:15:07,477] INFO Stat of the created znode at /brokers/ids/2 is: 342,342,1580624107474,1580624107474,1,0,0,72058698454728710,190,0,342
 (kafka.zk.KafkaZkClient)
[2020-02-01 22:15:07,477] INFO Registered broker 2 at path /brokers/ids/2 with addresses: ArrayBuffer(EndPoint(10.1.7.190,9092,ListenerName(PLAINTEXT),PLAINTEXT)), czxid (broker epoch): 342 (kafka.zk.KafkaZkClient)
[2020-02-01 22:15:07,527] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 10.1.7.190:9092 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:296)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:250)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2020-02-01 22:15:07,631] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 10.1.7.190:9092 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:296)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:250)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2020-02-01 22:15:07,737] WARN [Controller id=2, targetBrokerId=2] Error connecting to node 10.1.7.190:9092 (id: 2 rack: null) (org.apache.kafka.clients.NetworkClient)
java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:280)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:258)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:957)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:289)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:65)
	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:296)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:250)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
